title: Robert Godsmark # your name (or website title) here
logo: "/images/Robert Godsmark.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Game Developer and Programmer
  Aspiring Voice Actor
  <br><br>
  Second Year Birmingham City University Student
  Studying Computer Games Technology
  <br><br>
  <a href="https://www.linkedin.com/in/robert-godsmark-a07abb172/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
